TUI for user configuration done
GDGVIT/socrates-clients pull request #2
Opened 2020-10-23 16:12 UTC by SaurusXI

(Mostly done)
- Needs testing
- Needs integration once local API daemon is implemented

@L04DB4L4NC3R

2020-10-26 16:50 UTC, Geek-ubaid commented
@L04DB4L4NC3R review the PR and merge it, its getting stale.

2020-10-26 21:47 UTC, L04DB4L4NC3R requested changes

2020-10-26 21:47 UTC, L04DB4L4NC3R commented on settings/tui/tui.go
> +// // 1,000 most common English words.
Why is this being committed ?

2020-10-26 21:47 UTC, L04DB4L4NC3R commented on settings/tui/tui.go
> +func main() {
Setup log level on fn main

2020-10-26 21:47 UTC, L04DB4L4NC3R commented on settings/tui/screen/screen.go
> +	return &Screen{
Use better variable names than bb, db

2020-10-26 21:47 UTC, L04DB4L4NC3R commented on settings/tui/screen/screen.go
> +		AddItem(fb.Field, 0, 0, 1, 1, 0, 0, true).
Either use value names, or comment on what each value is in the args

2020-10-26 21:47 UTC, L04DB4L4NC3R commented on settings/tui/screen/elements/freq.go
> +	FreqFieldText = "Number of papers per day (max 5):"
Keep all these texts and prompts in a single const initialisation block

2020-10-26 21:47 UTC, L04DB4L4NC3R commented on settings/tui/screen/elements/domain.go
> +	padding := strings.Repeat(" ", len(FreqFieldText) - len(DomainFieldText))
Explanation needed

2020-10-26 21:47 UTC, L04DB4L4NC3R commented on settings/tui/screen/elements/buttons.go
> +	b.buttons = append(b.buttons[:idx], b.buttons[idx+1:]...)
Too many slicing and array deconstruction in one line. Mention the info in a comment

2020-10-26 21:47 UTC, L04DB4L4NC3R commented on TODO.md
> +- Add locally hosted API daemon for settings
Shift this section to the main README

2020-10-26 21:48 UTC, L04DB4L4NC3R commented
> @L04DB4L4NC3R review the PR and merge it, its getting stale.

Thanks for bringing it to my notice

2020-10-31 12:54 UTC, L04DB4L4NC3R commented
@SaurusXI do the changes

2020-11-01 11:13 UTC, SaurusXI commented
@L04DB4L4NC3R done, please review

2020-11-02 03:03 UTC, L04DB4L4NC3R approved these changes

2020-11-02 03:03 UTC, merged